//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMERA()
        {
            this.OFERTAs = new HashSet<OFERTA>();
            this.REZERVAREs = new HashSet<REZERVARE>();
        }
    
        public int id_camera { get; set; }
        public Nullable<int> id_tip { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> nr_camera { get; set; }
        public Nullable<int> etaj { get; set; }
        public Nullable<bool> valabilitate { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual TIPCAMERA TIPCAMERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFERTA> OFERTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZERVARE> REZERVAREs { get; set; }
    }
}
