//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public int id_oferta { get; set; }
        public Nullable<int> id_camera { get; set; }
        public string descriere { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public string pret_oferta { get; set; }
    
        public virtual CAMERA CAMERA { get; set; }
    }
}
