//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPCAMERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPCAMERA()
        {
            this.CAMERAs = new HashSet<CAMERA>();
        }
    
        public int id_tip { get; set; }
        public Nullable<int> id_imagine { get; set; }
        public Nullable<int> id_dotare { get; set; }
        public Nullable<int> id_serviciu { get; set; }
        public Nullable<int> capacitate { get; set; }
        public string nume { get; set; }
        public Nullable<int> pret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMERA> CAMERAs { get; set; }
        public virtual DOTARE DOTARE { get; set; }
        public virtual IMAGINE IMAGINE { get; set; }
        public virtual SERVICIU SERVICIU { get; set; }
    }
}
